export const ELEVENLABS_DEFAULT_VOICE_ID = "JBFqnCBsd6RMkjVDRZzb";
export const ELEVENLABS_ALLOWED_VOICE_IDS = [ELEVENLABS_DEFAULT_VOICE_ID] as const;
export const ELEVENLABS_TTS_MODEL_ID = "eleven_multilingual_v2";
export const ELEVENLABS_MAX_TTS_CHARACTERS = 500;
export const ELEVENLABS_LONG_PLAYBACK_THRESHOLD = 200;
